var $load=$("<div class='span_load'>&nbsp;</div>").addClass('load');var error=0;var cont_1=1;var $altura=$(window).height();var $ancho=$(window).width();var $loadimg="<img src='images/loader.gif'>";var $load=$("<div class='span_load'>&nbsp;</div>").addClass('load').css({"margin-top":($altura/2),"margin-left":($ancho/2-80)}).html("<img src='images/loader.gif'>");var $ajax_respuesta=$('<div id="ajax_respuesta" style="position: absolute; z-index:1000; float:right; background-color:#000"></div>').css({"margin-top":($altura/2),"margin-left":($ancho/2-80)});function mainmenu(){$(" #nav ul ").css({display:"none"});$(" #nav li").hover(function(){$(this).find('ul:first:hidden').css({visibility:"visible",display:"none"}).slideDown(400)},function(){$(this).find('ul:first').slideUp(400)})}
$(document).ready(function(e){if($.browser.msie){$("#cont_login").empty().html("<div class='msg alerta_err'><strong><h1>Explorador no funcional.</h1></strong></div>");return}
$(document).bind('keydown.ctrl_j',function(evt){return!1});m_left=($ancho-200)/2+'px';$(document).ajaxStart(function(){$.blockUI({message:$loadimg,fadeIn:20,fadeOut:50,overlayCSS:{backgroundColor:'#EFEFEF'},centerY:0,css:{width:'200px',backgroundColor:'#000',left:m_left,'-webkit-border-radius':'10px','-moz-border-radius':'10px','padding-top':'4px'}})}).ajaxError(function(){$.blockUI({message:'Error en el Servidor.',overlayCSS:{backgroundColor:'#FC2F2F'}});setTimeout($.unblockUI,1100)}).ajaxStop(function(){$.unblockUI()});$("#btn_login").button({text:!0,icons:{primary:"ui-icon-locked"}});$('#pwd').focus();$("#btn_login").click(function(){$pwd="";error=0;$('#cont_login').jrumble({x:5,y:2,rotation:3,speed:1,opacity:!1});$pwd=$('#pwd').val();valida_campo2(["pwd"],'','','',["pwd"],["#FFD13A"],["#E6FACB"]);if(error){$('#pwd').focus();$('#cont_login').trigger('startRumble');demoTimeout=setTimeout(function(){$('#login-box').trigger('stopRumble')},300);return}
$.ajax({type:"POST",contentType:"application/x-www-form-urlencoded",url:"funciones/valida_usr.php",data:"accion=valida_usr&pwd="+$pwd,beforeSend:function(){},success:function(data){var obj=jQuery.parseJSON(data);$('#ajax_respuesta_login').html("");$("#bar_top").show().empty();$("#inc_bienvenida").show();if(obj.tipo=="registrado"){$('#pwd').val('');$("#btn_login").hide();$("#cont_login").slideUp(250);$("#contenido").animate({opacity:.2},1000,function(){$("#contenido").animate({opacity:1},0);$("#contenido").css({top:'0px'});$("#bar_top").show().animate({width:"100%"},200,function(){$("#bar_top").append('<div id="ajax_respuesta" style="position: absolute; z-index:1000; background-color:#FFF; margin-left:'+($ancho-80)+'">load</div>');$.post("inc_menu_top.php",function(data){$("#bar_top").html(data)});$.post("inc_bienvenida.php",function(data){$("#inc_bienvenida").html(data)})})});$('#txt_IVA').val(obj.IVA);$('#txt_usr_nombre').val(obj.nombre);$('#txt_id_empresa').val(obj.id_empresa);$('#txt_id_sucursal').val(obj.id_sucursal);$('#txt_sucursal').val(obj.sucursal)}
if(obj.tipo=="no_resgistro"){$('#cont_login').trigger('startRumble');demoTimeout=setTimeout(function(){$('#login-box').trigger('stopRumble')},300);$('#ajax_respuesta_login').html("<div class='msg alerta f_rojo_claro t_negro'><strong>Acceso denegado.</strong></div>")}
if(obj.tipo=="errConexion"){$('#cont_login').trigger('startRumble');demoTimeout=setTimeout(function(){$('#login-box').trigger('stopRumble')},300);$('#ajax_respuesta_login').html("<div class='msg alerta f_rojo_claro t_negro'><strong>Problemas con el servidor.</strong></div>")}
if(obj.tipo=="inactivo"){$('#cont_login').trigger('startRumble');demoTimeout=setTimeout(function(){$('#login-box').trigger('stopRumble')},300);$('#ajax_respuesta_login').html("<div class='msg alerta f_rojo_claro t_negro'><strong>Cuenta Inactiva</strong></div>")}}});return})});function limpiar_datos(){$("div[id*='dialog']").remove();$("div[id*='popup']").remove();$("#contenido_resul ,#ajax_respuesta").empty()}
function enter_key_estatus(elEvento){var evento=elEvento||window.event;var caracter=evento.charCode||evento.keyCode;if(caracter==13){$("#btn_login").click()}}
function limita(maximoCaracteres,id,elEvento){var elemento=document.getElementById(id);var evento=elEvento||window.event;var caracter=evento.keyCode;if(elemento.value.length>=maximoCaracteres){if(caracter!=8)
return!1}
else{if(caracter==8&&elemento.value.length>0)
$("#num"+id).html(elemento.value.length-1);else if(caracter!=8){$("#num"+id).html(elemento.value.length+1);return!0}}}
function actualiza_sucursal_admin(){}
function cerrar_sistema(){$("#bar_top,#pie,#contenido_resul").fadeOut(400,function(){$("#contenido").css({top:'4.5%'});$("#contenido").animate({opacity:1},400,function(){$("#cont_login").fadeIn(450);$("#btn_login").show();$('#pwd').focus()});$("#bar_top,#pie").css({width:'5px'});$(".btn_menu").removeClass('btn_activo');$("#cont_bienvenida").hide();limpiar_datos()});$.post("funciones/cerrar_sesion.php",function(data){})}